# sudo apt-add-repository ppa:ansible/ansible && sudo apt update && sudo apt install ansible
# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --tags vagrant local.yml
---
- hosts: all
  remote_user: root
  roles:
    - display
    - common
    - packages
