---
- name: Atom | Add Atom Repository Key
  tags: [extras,3rd-packages,packages,atom]
  apt_key: keyserver=keyserver.ubuntu.com id=4C6E74D6C0A35108 state=present
#  apt_key:
#    url: https://packagecloud.io/AtomEditor/atom/gpgkey
#    state: present
- name: Atom | Add repository
  tags: [extras,3rd-packages,packages,atom]
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    filename: atom
- name: Atom | Install package
  tags: [extras,3rd-packages,packages,atom]
  package:
    name: atom
    state: latest
    update_cache: yes
