---
- name: aviDemux | Add GetDeb Repository
  tags: [extras,packages,avidemux]
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu xenial-getdeb apps
    filename: getdeb
- name: aviDemux | Add GetDeb Repository Key
  tags: [extras,packages,avidemux]
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present
- name: aviDemux | Install package
  tags: [extras,packages,avidemux]
  package:
    name: '{{ package }}'
    state: latest
    update_cache: yes
  with_items:
    - avidemux2.6-cli
    - avidemux2.6-qt
  loop_control:
    loop_var: package
