---
- name: aviDemux | Add 3rd Party PPA
  tags: [extras,3rd-packages,packages,avidemux]
  apt_repository:
    repo: ppa:ubuntuhandbook1/avidemux
    codename: bionic
- name: aviDemux | Install package
  tags: [extras,3rd-packages,packages,avidemux]
  package:
    name: '{{ package }}'
    state: latest
    update_cache: yes
  with_items:
    - avidemux2.6-cli
    - avidemux2.6-qt
    - avidemux2.6-plugins-qt
  loop_control:
    loop_var: package
- name: aviDemux | Remove 3rd party PPA
  tags: [extras,3rd-packages,packages,avidemux]
  apt_repository:
    repo: ppa:ubuntuhandbook1/avidemux
    codename: bionic
    state: absent
    update_cache: yes
