---
- name: DeadBeef | Add GetDeb Repository
  tags: [extras,packages,deadbeef]
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu xenial-getdeb apps
    filename: getdeb
- name: DeadBeef | Add GetDeb Repository Key
  tags: [extras,packages,deadbeef]
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present
- name: DeadBeef | Install package
  tags: [extras,packages,deadbeef]
  package:
    name: deadbeef
    state: latest
    update_cache: yes
