---
- name: Docker-CE | Add Repository
  tags: [extras,packages,docker]
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    filename: docker
- name: Docker-CE | Add Repository Key
  tags: [extras,packages,docker]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Docker-CE | Install package
  tags: [extras,packages,docker]
  package:
    name: docker.io
    state: latest
    update_cache: yes
- name: Docker-CE | Add User To Group
  tags: [extras,packages,docker]
  user:
    name: sander
    groups: docker
    append: yes
