---
- name: Dropbox | Install Dependencies
  tags: [extras,packages,dropbox]
  package:
    name: '{{item}}'
    state: latest
  with_items:
    # - python-gpgme Mint 18
    - python-gpg
- name: Dropbox | Install .deb Package
  tags: [extras,packages,dropbox]
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
