# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --tags etcher local.yml
---
- name: Etcher | Add Repository
  tags: [extras,packages,etcher]
  apt_repository:
    repo: deb https://dl.bintray.com/resin-io/debian stable etcher
    filename: etcher
- name: Etcher | Add Repository Key
  tags: [extras,packages,etcher]
  apt_key: keyserver=keyserver.ubuntu.com id=379CE192D401AB61 state=present
#  apt_key:
#    keyserver: hkp://pgp.mit.edu
#    id: 379CE192D401AB61
- name: Etcher | Install package
  tags: [extras,packages,etcher]
  package:
    name: etcher-electron
    state: latest
    update_cache: yes
