---
- name: FreeFileSync | mkdir
  tags: [extras,packages,freefilesync]
  file: path=/opt/FreeFileSync state=directory
- name: FreeFileSync | download package
  tags: [extras,packages,freefilesync]
  unarchive:
    src: 'https://www.freefilesync.org/download/FreeFileSync_9.5_Ubuntu_16.04_64-bit.tar.gz'
    dest: /opt/FreeFileSync
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: FreeFileSync | Download Logo
  tags: [extras,packages,freefilesync]
  get_url:
    url: https://www.freefilesync.org/images/FreeFileSync.png
    dest: /opt/FreeFileSync/FreeFileSync.png
    mode: 0644
- name: FreeFileSync | Create Launcher
  tags: [extras,packages,freefilesync]
  template:
    src: files/FreeFileSync.desktop
    dest: /usr/share/applications/FreeFileSync.desktop
    mode: 0644
- name: FreeFileSync | Symlink
  tags: [extras,packages,freefilesync]
  file:
    src: /opt/FreeFileSync/FreeFileSync
    dest: /usr/local/bin/FreeFileSync
    state: link
