---
- name: Google Chrome | Add Repository
  tags: [extras,packages,google-chrome]
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome-unstable
- name: Google Chrome | Add Repository Key
  tags: [extras,packages,google-chrome]
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Google Chrome | Install package
  tags: [extras,packages,google-chrome]
  package:
    name: google-chrome-unstable
    state: latest
    update_cache: yes
