---
- name: Google Drive | Add Repository
  tags: [extras,3rd-packages,packages,google-drive,never]
  apt_repository:
    repo: ppa:alessandro-strada/ppa
    codename: bionic
- name: Google Drive | Install package
  tags: [extras,3rd-packages,packages,google-drive,never]
  package:
    name: google-drive-ocamlfuse
    state: latest
    update_cache: yes
