---
- name: NextCloud Client | Add Repository
  tags: [extras,packages,nextcloud]
  apt_repository:
    repo: ppa:nextcloud-devs/client
    codename: bionic
- name: NextCloud Client | Install Dependencies
  tags: [extras,packages,nextcloud]
  package:
    name: '{{item}}'
    state: latest
  with_items:
    - libgnome-keyring0
- name: NextCloud Client | Install package
  tags: [extras,packages,nextcloud]
  package:
    name: nextcloud-client
    state: latest
    update_cache: yes
