# env ANSIBLE_NOCOWS=1 sudo ansible-playbook --tags nextcloud local.yml
---
- name: NextCloud Client | Add repository
  tags: [nextcloud,never]
  apt_repository:
    repo: ppa:nextcloud-devs/client
    codename: bionic
- name: NextCloud Client | Install package and dependencies
  tags: [nextcloud,never]
  package:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items:
    - libgnome-keyring0
    - nextcloud-client
