---
- name: Packages | Update Cache
  tags: [extras,packages,official]
  apt:
    update_cache: yes
- name: Packages | Install Official Packages
  tags: [extras,packages,official]
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - aspell
    - aspell-en
    - aspell-nl
    - audacity
    - bleachbit
    - chkrootkit
    - clamtk
    - composer
    - conky-all
    - exfat-fuse
    - exfat-utils
    - feh
    - ffmpeg
    - filezilla
    - fslint
    - geany
    - geany-plugins
#    - geany-plugin-markdown # not in Mint 19
    - gimp
    - git
    - gitk
    - gmpc
    - gparted
    - gprename
    - hddtemp
    - hdparm
    - imagemagick
    - keepassx
    - lmms
    - mediainfo-gui
    - meld
    - mplayer
    - mpv
    - ocrfeeder
    - openssh-client
#    - pdfchain # not in Mint 19
    - pixz
    - puddletag
    - pv
#    - pyrenamer # not in Mint 19
    - python-termcolor
    - python-keyring
    - python-vsgui
    - rkhunter
    - screen
    - smartmontools
    - software-properties-common
    - sshfs
    - terminator
    - tomboy
    - unrar
    - xclip
    - youtube-dl
- name: Packages | Remove Unwanted Packages
  tags: [extras,packages,packages,official]
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - hexchat

# TODO:
# gscan2pdf from https://sourceforge.net/projects/gscan2pdf/
# ttf-*
# fonts-*
