# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --tags robo3t local.yml
---

- name: Robo3T | Get main user
  tags: [extras,3rd-packages,packages,robo3t]
  shell: id -nu 1000
  register: get_user_by_id
- name: Robo3T | Register main user
  tags: [extras,3rd-packages,packages,robo3t]
  set_fact:
    user: "{{get_user_by_id.stdout}}"
- debug:
    var: user

- name: Robo3T | mkdir
  tags: [extras,3rd-packages,packages,robo3t]
  file:
    path: '/home/{{user}}/opt/Robo3T'
    state: directory
    mode: 0750
    owner: '{{user}}'
    group: '{{user}}'

- name: Robo3T | Grab download link
  tags: [extras,3rd-packages,packages,robo3t]
  shell: wget -O - https://robomongo.org/download | grep 'linux-x86_64' | grep '.tar.gz' | sed -n 's/.*href="\(.*\)">robo3t-[0-9\.]*-linux-x86_64.*/\1/p'
  args:
    warn: false
  register: robo3t_url
- name: Robo3T | Download package
  tags: [extras,3rd-packages,packages,robo3t]
  unarchive:
    src: '{{robo3t_url.stdout}}'
    dest: '/home/{{user}}/opt/Robo3T'
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: '{{user}}'
    group: '{{user}}'

# Necessary, given https://github.com/ansible/ansible/issues/35426
- name: Robo3T | Fix permissions
  tags: [extras,3rd-packages,packages,robo3t]
  file:
    path: '/home/{{user}}/opt/Robo3T'
    owner: '{{user}}'
    group: '{{user}}'
    mode: 'o-rwx'
    recurse: yes

- name: Robo3T | Create launcher
  tags: [extras,3rd-packages,packages,robo3t]
  template:
    src: files/Robo3T.desktop
    dest: '/home/{{user}}/.local/share/applications/Robo3T.desktop'
    mode: 0640
    owner: '{{user}}'
    group: '{{user}}'

- name: Robo3T | Set logo
  tags: [extras,3rd-packages,packages,robo3t]
  copy:
    src: files/robo3t.png
    dest: '/home/{{user}}/.local/share/icons/robo3t.png'
    mode: 0640
    owner: '{{user}}'
    group: '{{user}}'

# - name: Update launcher
#   tags: [extras,3rd-packages,packages,robo3t]
#   lineinfile:
#     path: '/home/{{user}}/.local/share/applications/Robo3T.desktop'
#     regexp: '^{{item.key}}='
#     line: '{{item.key}}={{item.value}}'
#   with_items:
#     - { key: 'Exec', value: '/home/{{user}}/opt/Robo3T/bin/robo3t' }
