# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --tags terminator local.yml
---
- name: Terminator | Add repository
  tags: [extras,packages,terminator]
  apt_repository:
    repo: ppa:gnome-terminator
    codename: xenial
- name: Terminator | Install package
  tags: [extras,packages,terminator]
  package:
    name: terminator
    state: latest
    update_cache: yes
