---
- name: Tilix | Add repository
  tags: [never,extras,3rd-packages,packages,tilix]
  apt_repository:
    repo: ppa:webupd8team/terminix
    codename: bionic
- name: Tilix | Install package
  tags: [never,extras,3rd-packages,packages,tilix]
  package:
    name: tilix
    state: latest
    update_cache: yes
