---
- name: Vagrant | Find latest version
  tags: [never,extras,packages,vagrant]
  shell: wget -O - https://www.vagrantup.com/downloads.html | grep x86_64.deb | head -n1 | sed -n 's/.*<a href="\([^"]*\)".*/\1/p'
  register: deb_url
- name: Vagrant | Install package
  tags: [never,extras,packages,vagrant]
  apt:
    deb: '{{deb_url.stdout}}'
