# env ANSIBLE_NOCOWS=1 ansible-playbook --ask-become-pass --tags vidcutter local.yml
---
- name: VidCutter | Add repository
  tags: [extras,packages,vidcutter]
  apt_repository:
    repo: ppa:ozmartian/apps
    codename: xenial
- name: VidCutter | Install package
  tags: [extras,packages,vidcutter]
  package:
    name: vidcutter
    state: latest
    update_cache: yes
