---
- name: VirtualBox | Add repository
  tags: [extras,packages,virtualbox]
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    filename: virtualbox
- name: VirtualBox | Add repository key
  tags: [extras,packages,virtualbox]
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
# - name: VirtualBox | Install package
#   tags: [extras,packages,virtualbox]
#   package:
#     name: "{{ item }}"
#     state: latest
#     update_cache: yes
#   with_items:
#     - virtualbox-5.2
#     - virtualbox-qt # not available for 5.2
#     - virtualbox-ext-pack # not available for 5.2
# https://www.virtualbox.org/wiki/Downloads
# http://download.virtualbox.org/virtualbox/5.2.2/Oracle_VM_VirtualBox_Extension_Pack-5.2.2-119230.vbox-extpack
# vboxmanage extpack install --replace /path/to/ext-pack
