# sudo ansible-playbook local.yml -t virtualbox
---
# Get main user
- name: VirtualBox | Get main user
  tags: [never,extras,virtualbox]
  shell: id -nu 1000
  register: get_user_by_id
- name: Docker-CE | Store main user
  tags: [extras,3rd-packages,packages,docker]
  set_fact:
    user: "{{get_user_by_id.stdout}}"

- name: VirtualBox | Add repository key
  tags: [never,extras,virtualbox]
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: VirtualBox | Add repository
  tags: [never,extras,virtualbox]
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bionic contrib
    filename: virtualbox
- name: VirtualBox | Remove old versions
  tags: [never,extras,virtualbox]
  package:
    name: "{{ item }}"
    state: absent
    update_cache: no
  with_items:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-guest-utils
- name: VirtualBox | Install package
  tags: [never,extras,virtualbox]
  package:
    name: virtualbox-5.2
    state: latest
    update_cache: yes
  register: vbox
- name: VirtualBox | Find guest additions
  tags: [never,extras,virtualbox]
  shell: wget -O - https://www.virtualbox.org/wiki/Downloads | grep Oracle_VM_VirtualBox_Extension_Pack | sed -n 's/.*<a class="ext-link" href="\([^"]*\)".*/\1/p'
  register: extpack_url
  when: vbox.changed
- name: VirtualBox | Get guest additions filename
  tags: [never,extras,virtualbox]
  shell: "basename {{extpack_url.stdout}}"
  register: extpack_filename
  when: vbox.changed
- name: VirtualBox | Download guest additions
  tags: [never,extras,virtualbox]
  get_url:
    url: "{{extpack_url.stdout}}"
    dest: "/tmp/{{extpack_filename.stdout}}"
  when: vbox.changed
- name: VirtualBox | Install guest additions
  tags: [never,extras,virtualbox]
  shell: "echo y | vboxmanage extpack install --replace /tmp/{{extpack_filename.stdout}}"
  when: vbox.changed

- name: VirtualBox | Add main user to vboxusers group
  tags: [never,extras,virtualbox]
  user:
    name: '{{user}}'
    groups: vboxusers
    append: yes
