---
- name: XnViewMP | Add GetDeb Repository
  tags: [extras,packages,xnviewmp]
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu xenial-getdeb apps
    filename: getdeb
- name: XnViewMP | Add GetDeb Repository Key
  tags: [extras,packages,xnviewmp]
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present
- name: XnViewMP | Install package
  tags: [extras,packages,xnviewmp]
  package:
    name: xnviewmp
    state: latest
    update_cache: yes
