---
- name: Set login screen to HiDPI mode
  tags: [extras,lightdm,hidpi,never]
  when: ansible_distribution == 'LinuxMint'
  lineinfile:
    path: /etc/lightdm/lightdm-gtk-greeter.conf.d/99_linuxmint.conf
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'xft-dpi', value: '192' }
