---
# Note: This one is only relevant with multiple boot options
- name: Grub | Hide grub menu and lower timeout
  tags: [extras,grub]
  lineinfile:
    path: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'GRUB_HIDDEN_TIMEOUT', value: '3' }
    - { key: 'GRUB_HIDDEN_TIMEOUT_QUIET', value: 'true' }
    - { key: 'GRUB_TIMEOUT', value: '3' }
    - { key: 'GRUB_TIMEOUT_STYLE', value: 'countdown' }
- name: Grub | Update
  tags: [extras,grub]
  command: update-grub
  become: true
